### PR TITLE
[build] Fix arch detection

### PR DESCRIPTION
**Pull request by krono**
On ppc64le deb machines, when _not_ cross compiling, `uname -m` reports `ppc64le`, which is typically right. However, the "Debian machine triplet" that is necessary to build correctly uses `powerpc64le` for whatever reason. The cross compile path knows this and is explicit about that.

To alleviate that, use `dpkg-architecture` to discover the HOST _CPU_ type, which is what forms the machine triplet. The conditional check for `dpkg-architecture` should be safe and reports the right values for x86 and arm, too; falls back to `uname -m` anyways.

### CODE REVIEW

**Comment by 3XX0** [comment]
Right... this is messy.
Correct me if I'm wrong but we want the GNU triplet here, not the Debian one. Debian is `ppc64el`, GNU is `powerpc64le`
I think we tried to account for it judging by [this](https://github.com/NVIDIA/enroot/blob/b73986ae50b075601be393108d97dae1f50943a1/Makefile#L89) but this might not even be correct w.r.t `el`/`le`.

Could we make this a little more generic?
IIRC `dpkg-architecture` relies on `$CC -dumpmachine`, just wondering if we could just do that

**Comment by krono** [comment]
It's `debuild` that invokes some `dh_` stuff, which is unhappy with `ppc64le-gnu-linux`, because it wants `powerpc64le-gnu-linux`.

* `uname -m` result in  `ppc64le`
* we already _know_ we need `powerpc64le` because we explicitely set it when cross-compiling in https://github.com/NVIDIA/enroot/blob/master/pkg/debbuild#L60

but `-dumpmachine` sounds plausible…

**Comment by krono** [comment]
I switchted the approach to dumpmachine, but deb-specific.

**Comment by 3XX0** [comment]
LGTM, feel free to sign off the commit so I can merge it

**Comment by krono** [comment]
Hope this was the righ swithc :D

**Pull request merged**
